---
title: "Analysis of Test Results"
author: "Team GreenBeans"
date: "2023-09-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results = "hide",fig.show = 'hide'  )
```

```{r}
library(tidyverse)
library(car)
library(effsize)
```

```{r}
data <- read.csv("../../data/processed/data.csv")
data
```

## Convert columns to factor and numeric type

```{r}
data$concat <- as.factor(data$concat)
data$queue_limit <- as.factor(data$queue_limit)
data$ncores <- as.factor(data$ncores)
data$ConsumedEnergy <- as.numeric(gsub("K", "e3", data$ConsumedEnergy))


# HH:MM:SS is converted into an integer of seconds
data$Elapsed <- sapply(strsplit(data$Elapsed,":"),
  function(x) {
    x <- as.numeric(x)
    x[1]*3600+x[2]*60+x[3]
    }
)
```

## Select data of modes HPC and local
```{r}
data_hpc <- data %>%
  filter(mode == "hpc")
data_local <- data %>%
  filter(mode == "local")
```

## Test normality of ConsumedEnergy
### Graphical
```{r}
ggplot(data_hpc, aes(x = ConsumedEnergy)) + 
  geom_histogram()
ggplot(data_local, aes(x = ConsumedEnergy)) + 
  geom_histogram()
ggplot(data, aes(x=mode, y=ConsumedEnergy)) +
          geom_violin(trim=FALSE, alpha = 0.8) + # alpha for the opacity
          geom_boxplot(width=0.2, fill="white", outlier.size = 0.2) +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot with Inner Boxplot",
          x="mode",
          y="Consumed Energy")
qqPlot(data_hpc$ConsumedEnergy)
qqPlot(data_local$ConsumedEnergy)
```
### Statistical Tests
```{r}
# HPC
shapiro.test(data_hpc$ConsumedEnergy)
ks.test(data_hpc$ConsumedEnergy, "pnorm")

# Local
shapiro.test(data_local$ConsumedEnergy)
ks.test(data_local$ConsumedEnergy, "pnorm")
```
## Test normality of Runtime
### Graphical
```{r}
ggplot(data_hpc, aes(x = Elapsed)) + 
  geom_histogram()
ggplot(data_local, aes(x = Elapsed)) + 
  geom_histogram()
ggplot(data, aes(x=mode, y=Elapsed)) +
          geom_violin(trim=FALSE, alpha = 0.8) + # alpha for the opacity
          geom_boxplot(width=0.2, fill="white", outlier.size = 0.2) +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot with Inner Boxplot",
          x="mode",
          y="Runtime")
qqPlot(data_hpc$Elapsed)
qqPlot(data_local$Elapsed)
```
### Statistical Tests
```{r}
# HPC
shapiro.test(data_hpc$Elapsed)
ks.test(data_hpc$Elapsed, "pnorm")

# Local
shapiro.test(data_local$Elapsed)
ks.test(data_local$Elapsed, "pnorm")
```
## Mann-Whitney-Wilcoxon Test: local vs hpc
```{r}
wilcox.test(data_local$ConsumedEnergy, data_hpc$ConsumedEnergy, alternative = "greater")
cliff.delta(data_local$ConsumedEnergy, data_hpc$ConsumedEnergy)

wilcox.test(data_local$Elapsed, data_hpc$Elapsed, alternative = "less")
cliff.delta(data_local$Elapsed, data_hpc$Elapsed)
```
## Factors in mode local

```{r}
ggplot(data_local, aes(x = ncores, y = ConsumedEnergy)) + 
  facet_grid(NodeList ~ ncores, labeller=label_both, scales='fixed') +
  stat_summary(fun = mean, geom = "bar") 
ggplot(data_local, aes(x = ncores, y = Elapsed)) + 
  facet_grid(NodeList ~ ncores, labeller=label_both, scales='fixed') +
  stat_summary(fun = mean, geom = "bar")
ggplot(data_local, aes(x=ncores, y=ConsumedEnergy)) +
          geom_boxplot() +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot with Inner Boxplot",
          x="ncores",
          y="Consumed Energy")
ggplot(data_local, aes(x=ncores, y=Elapsed)) +
          geom_boxplot() +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot with Inner Boxplot",
          x="ncores",
          y="Runtime")

data_local %>%
  group_by(ncores)%>%
  summarize(n=n(),
            mean = mean(ConsumedEnergy),
            median = median(ConsumedEnergy),
            sd = sd (ConsumedEnergy),
            IQR = IQR (ConsumedEnergy),
            min = min (ConsumedEnergy),
            max = max (ConsumedEnergy)
            )

data_local %>%
  group_by(ncores)%>%
  summarize(n=n(),
            mean = mean(Elapsed),
            median = median(Elapsed),
            sd = sd (Elapsed),
            IQR = IQR (Elapsed),
            min = min (Elapsed),
            max = max (Elapsed)
            )
interaction.plot(data_local$ncores, data_local$NodeList, data_local$ConsumedEnergy)
interaction.plot(data_local$ncores, data_local$NodeList, data_local$Elapsed)
```
```{r}
# Additive Model without Interaction
lm_local <- lm(ConsumedEnergy ~ ncores + NodeList, data = data_local)
anova(lm_local)
summary(lm_local)
qqPlot(residuals(lm_local))
friedman.test(data_local$ConsumedEnergy, data_local$ncores, data_local$NodeList)
```



## Factors in mode HPC

```{r}
ggplot(data_hpc, aes(x = ConsumedEnergy)) + 
  geom_histogram() + 
  facet_grid(queue_limit ~ concat, labeller=label_both, scales = "free")
```

```{r}
ggplot(data_hpc, aes(x = Elapsed)) + 
  geom_histogram() + 
  facet_grid(queue_limit ~ concat, labeller=label_both, scales='free')
```



```{r}
ggplot(data_hpc, aes(x=concat, y=ConsumedEnergy, fill=concat)) + geom_boxplot() +
  stat_summary(fun = mean,color= 'red', geom = "point", shape = 1, size = 2) +
  labs(title="Box Plots",
  x="concat",
  y="Energy consumed") 
```

```{r}
violin <- ggplot(data_hpc, aes(x=concat, y=ConsumedEnergy, fill=concat)) +
          geom_violin(trim=FALSE, alpha = 0.8) + # alpha for the opacity
          geom_boxplot(width=0.2, fill="white", outlier.size = 0.2) +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot",
          x="concat",
          y="Energy consumed") 
violin
```

## Graphical summary of Runtime

```{r}
ggplot(data_hpc, aes(x=concat, y=Elapsed, fill=concat)) + geom_boxplot() +
  stat_summary(fun = mean,color= 'red', geom = "point", shape = 1, size = 2) +
  labs(title="Box Plots",
  x="concat",
  y="Runtime") 
```

```{r}
ggplot(data_hpc, aes(x=concat, y=Elapsed, fill=concat)) +
          geom_violin(trim=FALSE, alpha = 0.8) + # alpha for the opacity
          geom_boxplot(width=0.2, fill="white", outlier.size = 0.2) +
          stat_summary(fun = mean, geom = "point", shape = 1, size = 2) +
          labs(title="Violin Plot of runtime",
          x="concat",
          y="Runtime") 
```

